import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#d4c3ba",
        "secondary-fixed-dim": "#e6c367",
        "surface-container-highest": "#e6e1e1",
        primary: "#665952",
        "on-tertiary-fixed-variant": "#474743",
        "inverse-surface": "#313030",
        "on-primary-container": "#fffbff",
        "on-primary-fixed-variant": "#50443d",
        "error-container": "#ffdad6",
        "surface-container-high": "#ece7e7",
        surface: "#fdf8f8",
        "surface-tint": "#695c54",
        background: "#fdf8f8",
        "tertiary-container": "#767471",
        "on-secondary-container": "#785d05",
        "on-tertiary-fixed": "#1c1c19",
        "inverse-on-surface": "#f4f0ef",
        "surface-container-low": "#f7f2f2",
        "secondary-fixed": "#ffdf91",
        "primary-fixed": "#f1dfd5",
        "on-secondary-fixed-variant": "#584400",
        "surface-container": "#f1edec",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#241a00",
        "on-error": "#ffffff",
        error: "#ba1a1a",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#231a14",
        "on-background": "#1c1b1b",
        tertiary: "#5d5c58",
        "on-surface-variant": "#4e4540",
        "surface-bright": "#fdf8f8",
        "tertiary-fixed": "#e5e2dd",
        secondary: "#755b02",
        outline: "#80756f",
        "outline-variant": "#d1c4bd",
        "secondary-container": "#fdd97a",
        "primary-fixed-dim": "#d4c3ba",
        "surface-dim": "#ddd9d9",
        "tertiary-fixed-dim": "#c9c6c2",
        "primary-container": "#80726a",
        "surface-variant": "#e6e1e1",
        "on-primary": "#ffffff",
        "on-surface": "#1c1b1b",
        "on-tertiary-container": "#fcffe3",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px",
        "margin-desktop": "64px",
        unit: "8px",
        "container-max": "1200px",
        "margin-mobile": "16px",
        gutter: "24px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        "label-md": ["var(--font-inter)"],
        "headline-md": ["var(--font-playfair)"],
        "body-md": ["var(--font-inter)"],
        "headline-lg-mobile": ["var(--font-playfair)"],
        "headline-lg": ["var(--font-playfair)"],
        "display-lg": ["var(--font-playfair)"],
        caption: ["var(--font-inter)"],
        "body-lg": ["var(--font-inter)"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "headline-lg": ["40px", { lineHeight: "48px", fontWeight: "500" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
      boxShadow: {
        ambient: "0 10px 40px rgba(87, 85, 85, 0.08)",
      },
    },
  },
  plugins: [],
};

export default config;
